<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_AbsorptionChiller" Id="{58c6b46c-a56b-418c-b518-17d466272f79}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AbsorptionChiller
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AbsorptionChiller">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>