<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_HNLTMachineSystem" Id="{9e31bb33-93a7-4fc1-a5d6-51b03d50941a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HNLTMachineSystem
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HNLTMachineSystem">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>