<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_AnnealingOven" Id="{55cd34b0-1d7f-435c-9435-b7ad14b8fb75}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AnnealingOven
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AnnealingOven">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>