<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_Compressor" Id="{64ad3e54-80e9-4a0f-b456-d3f5d72b18fd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Compressor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Compressor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>