<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_DCControl" Id="{8c229838-3742-48b4-a907-91e08ed4966e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DCControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_DCControl">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>