<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_EmagGT" Id="{4cf53386-82f7-4bad-a149-3dcf35915689}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_EmagGT
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_EmagGT">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>