<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_MafacJava" Id="{9ab89f15-d411-40eb-9781-2f3a2eb9a02c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MafacJava
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_MafacJava">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>