<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_Ventilation" Id="{94cdc637-68fc-4965-95c2-bd12607af2ac}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Ventilation
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Ventilation">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>