<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_BufferStorage" Id="{8e38393d-195d-45df-94d3-1eb118fb470f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BufferStorage
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	UpperTemperatureSensor : FB_TemperatureSensor; //upper temperature sensor
	MidTemperatureSensor : FB_TemperatureSensor; //mid temperature sensor
	LowerTemperatureSensor : FB_TemperatureSensor; //lower temperature sensor
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//get sensor inputs
UpperTemperatureSensor.SetState_AI();
MidTemperatureSensor.SetState_AI();
LowerTemperatureSensor.SetState_AI();]]></ST>
    </Implementation>
    <LineIds Name="FB_BufferStorage">
      <LineId Id="24" Count="2" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>