<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_PumpGrundfosCM" Id="{5b6d9bd2-ce18-456b-8ae2-afbacf79793a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PumpGrundfosCM EXTENDS FB_Actor2Point
VAR
	//I/O Links
	bSetStatusOn_OUT 	AT %Q* : BOOL := FALSE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="SetState_BO" Id="{36b0dedc-9e39-443a-8eb0-332e87306b63}">
      <Declaration><![CDATA[METHOD SetState_BO : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[//output
bSetStatusOn_OUT := bSetStatusOn;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_PumpGrundfosCM">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_PumpGrundfosCM.SetState_BO">
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>