<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_CondensingBoiler" Id="{a735ace5-71e9-497d-839f-87ce45582673}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CondensingBoiler
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_CondensingBoiler">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>