<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_ImmersionHeater" Id="{2de23c48-52f9-4c7c-a711-bae727744ee8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ImmersionHeater
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ImmersionHeater">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>