<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_CHPSystem" Id="{400ace1e-f656-4c3e-b9b1-7a0a907f409b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CHPSystem
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	//discrete valve SV32x, controled mixing valve RV32x, pump PU32x
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_CHPSystem">
      <LineId Id="19" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>