<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="HeatCounter" Id="{4204b3f6-5c13-42c2-93aa-e47631f91a16}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM HeatCounter
VAR
	test_output : REAL;
	
	//cycle counter
	HeatCounter_CycleCount : UDINT;
    info  : GETCURTASKINDEX;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//test output for checking variable exchange between tasks with different cycle time
test_output := 1;
info();
HeatCounter_CycleCount := _TaskInfo[info.index].CycleCount;]]></ST>
    </Implementation>
    <LineIds Name="HeatCounter">
      <LineId Id="14" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>