<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{9f33f5a0-2a24-4206-9468-c589128c5602}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	testSystem : FB_TestSystem;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[testSystem();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>