<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_PWT1System" Id="{61964d8e-51ba-4d03-8634-2a417c9ac9b4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PWT1System
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_PWT1System">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>