<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_AnnealingOvenSystem" Id="{1d6232b5-61ec-4b2a-9b17-24b9b5f900d1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AnnealingOvenSystem
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AnnealingOvenSystem">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>