<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_HallHeatingSystem" Id="{f8442f79-4535-4a98-a2d3-562d56bde7d4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HallHeatingSystem
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HallHeatingSystem">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>