<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_StaticHeatingSystem" Id="{47923f72-ad6c-4025-8311-45ce8250a43c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_StaticHeatingSystem
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_StaticHeatingSystem">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>