<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_UnderfloorHeatingSystem" Id="{f2af6b83-4cb8-4b49-a3ac-8e5a68fc4df4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_UnderfloorHeatingSystem
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_UnderfloorHeatingSystem">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>