<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_VentilationSystem" Id="{a8973b76-fc15-4847-b6a0-15c8e3d202d2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_VentilationSystem
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_VentilationSystem">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>