<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_MollineC3HeatCounter" Id="{68b26994-e772-43d9-bb19-4685b29f39a6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MollineC3HeatCounter
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	{attribute 'OPC.UA.DA' := '1'}
	sensorState : ST_MollineC3HeatCounterState;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_MollineC3HeatCounter">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>