<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_HybridEnergyStorage" Id="{d0e73ddc-d48c-401f-86b9-ea00e651427d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HybridEnergyStorage
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HybridEnergyStorage">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>