<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="LowTemperatureHeatingNetwork" Id="{41e3edb3-66e7-411c-a35e-b44e9a5d66f1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LowTemperatureHeatingNetwork
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="LowTemperatureHeatingNetwork">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>